### ISSUE TITLE
Attributes in can-autorender tags are not encoded with can-attribute-encoder

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-view-autorender#70]
This was reported [here](https://gitter.im/canjs/canjs?at=5a035ab2f257ad91096e287c) and this [repo](https://github.com/pYr0x/can-view-autorender-bug) can be used to see the issue.

If you have stache-bindings inside of a `can-autorender` tag, they won't work because they are not encoded:

```
<x-first vm:fooBar:from="scope.vars.foo"></x-first>
Reference: {{scope.vars.foo}}
```

If you manually encode `vm:fooBar:from` to `vm:foo:u:bar:from`, then it will work correctly.

**Comment by imaustink** [comment]
`can-view-autorender` actually does use `can-attribute-encoder`. This problem is actually caused by a limitation of the DOM. When an element with an attribute name that has uppercase characters is inserted into the DOM, the attribute name is lowercased. See example: https://jsfiddle.net/kkjsLmgy/1/

In this example, `can-attribute-encoder` is getting `vm:foobar:from` instead of `vm:fooBar:from`. As far as I can tell, there isn't anything we can do about this. In this edge case, the workaround would be to just manually encode it.

**Comment by imaustink** [comment]
cc @pYr0x

**Comment by pYr0x** [comment]
thank you very much
